import Head from "next/head";


const HeadPart = () => {
  return (
    <Head>
        <title>Star Wars Characters</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link href="https://api.fontshare.com/v2/css?f[]=general-sans@200,500,301,1,300,600,700&display=swap" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
    </Head>
  )
}

export default HeadPart